"""init

Revision ID: dc2b20e9bfc4
Revises: ae9657bf0f09
Create Date: 2025-12-28 10:22:37.331994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'dc2b20e9bfc4'
down_revision = 'ae9657bf0f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = {col["name"] for col in inspector.get_columns("bicycles")}
    with op.batch_alter_table('bicycles', schema=None) as batch_op:
        if 'description' not in columns:
            batch_op.add_column(sa.Column('description', sa.String(length=300), nullable=True))
        if 'serial_number' in columns:
            batch_op.drop_column('serial_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = {col["name"] for col in inspector.get_columns("bicycles")}
    with op.batch_alter_table('bicycles', schema=None) as batch_op:
        if 'serial_number' not in columns:
            batch_op.add_column(sa.Column('serial_number', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        if 'description' in columns:
            batch_op.drop_column('description')

    # ### end Alembic commands ###
